trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*

stages:
- stage: CI
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/feature/docker_impl'))
  jobs: 
  - job: BuildImage
    steps:
    - script: ls -la
      displayName: 'Build docker image'   


# Continuous Deployment Process for Staging Environment
- stage: DeployToStaging
  jobs:
  - job:
    steps:
    - script: ls -la
      displayName: 'Build docker image' 
          


# Continuous Delivery Process for Production Environment
- stage: DeployToProduction
  jobs:
  - job:
    steps:
    - script: ls -la
      displayName: 'Build docker image' 