trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*

stages:
- stage: CI
  jobs: 
  - job: BuildImage
    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker 17.09.0-ce'
    - task: Docker@2
      displayName: build
      inputs:
        containerRegistry: 'docker-registry'
        repository: 'weight-tracker'
        command: build
        #tags: 'weight-tracker:1.$(Build.BuildId)'
        arguments: 'IMG_VER=1.$(Build.BuildId)'
        addPipelineData: false
        addBaseImageData: false
    - task: Docker@2
      displayName: push
      inputs:
        containerRegistry: 'docker-registry'
        repository: 'weight-tracker'
        command: push
- stage: DeployToStage 
  jobs:
  - job: BuildImage
    steps: 
    - script: |
        ls -la